theme = "gruvbox"

[editor]
line-number = "relative"
scrolloff = 5
idle-timeout = 0
auto-pairs = false
color-modes = true
cursorline = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.whitespace.characters]
tab = "→"
