theme = "gruvbox"

[editor]
line-number = "relative"
scrolloff = 5
idle-timeout = 0
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
tab = "→"