theme = "catppuccin_mocha"

[editor]
line-number = "relative"
scrolloff = 5
idle-timeout = 0
auto-pairs = false
color-modes = true
cursorline = true
true-color = true
rulers = []

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[editor.file-picker]
hidden = false

[keys.normal.space]
o = [":format", ":write"]

