[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
# formatter = { command = "rustfmt" }
auto-format = true
[language-server.rust-analyzer]
command = "rust-analyzer"
[language-server.rust-analyzer.config.check]
command = "clippy"
[language-server.rust-analyzer.config.cargo]
features = "all" 
[language-server.rust-analyzer.config.procMacro]
enable = true 

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "toml"] }

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true


[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "verilog"
language-servers = ["svls"]

[[language]]
name = "scheme"
file-types = ["lisp", "cl", "el", "mud", "asd"]
language-servers = ["cl"]

[[language]]
name = "markdown"
roots = [".marksman.toml"]
language-servers = ["marksman", "github-lsp"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }

[language-server.svls]
command = "svls"

[language-server.cl]
command = "cl-lsp"
args = ["stdio"]

[language-server.marksman]
command = "marksman"
args = ["server"]

[language-server.github-lsp]
command = "github-lsp"
# args = ["server"]
