[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }
cargo = { allFeatures = true }
procMacro = { enable = true }

[[language]]
name = "verilog"
language-servers = ["svls"]

[[language]]
name = "scheme"
file-types = ["lisp", "cl", "el", "mud", "asd"]
language-servers = ["cl"]

[[language]]
name = "markdown"
roots = [".marksman.toml"]
language-servers = ["marksman"]

[language-server.svls]
command = "svls"

[language-server.cl]
command = "cl-lsp"
args = ["stdio"]

[language-server.marksman]
command = "marksman"
args = ["server"]
