source $VIMRUNTIME/defaults.vim
source ~/.vim/set.vim
source ~/.vim/plugins.vim
source ~/.vim/bindings.vim
source ~/.vim/run.vim

let g:lightline = {'colorscheme':'gruvbox'}

syntax on
colorscheme gruvbox

set background=dark
