source $VIMRUNTIME/defaults.vim
source ~/.vim/set.vim
source ~/.vim/plugins.vim
source ~/.vim/bindings.vim

syntax on
set background=dark
colorscheme gruvbox

" let g:lightline = {'colorscheme':'gruvbox'}
