format = '$all$directory$character'

[shell]
disabled = false
fish_indicator = "λ"
bash_indicator = "β"
nu_indicator = "η"

[gcloud]
disabled = true

[kubernetes]
format = '[$symbol$context\($namespace\)](green) '
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'local'
'gke_.*_(?P<var_cluster>[\w-]+)' = '$var_cluster'
